# Generated by Django 4.2.7 on 2023-11-13 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estado_habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estado', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_habitacion', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=500)),
                ('precioxnoche', models.FloatField()),
                ('cantidad_adultos', models.IntegerField()),
                ('cantidad_ninos', models.IntegerField()),
                ('foto', models.ImageField(upload_to='fotos_tipoHab')),
            ],
        ),
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('num_habitacion', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('id_estadoHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_room.estado_habitacion')),
                ('id_tipoHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_room.tipo_habitacion')),
            ],
        ),
    ]
