# Generated by Django 4.2.7 on 2023-11-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_inventory', '0001_initial'),
        ('mod_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventarioxhabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_inventory.inventario')),
                ('num_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_room.habitacion')),
            ],
        ),
    ]
