# Generated by Django 4.2.7 on 2023-12-04 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_user', '0001_initial'),
        ('mod_guest', '0001_initial'),
        ('mod_room', '0002_inventarioxhabitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('precio_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_adultos', models.IntegerField()),
                ('cantidad_ninos', models.IntegerField()),
                ('numero_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_user.persona')),
            ],
        ),
        migrations.CreateModel(
            name='huespedxreserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_reservation.reserva')),
                ('nro_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_guest.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='habitacionxreserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_reservation.reserva')),
                ('num_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_room.habitacion')),
            ],
        ),
    ]
