# Generated by Django 4.2.6 on 2023-11-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField()),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_detalleFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_invoice.detallesfactura')),
                ('id_metodoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_invoice.metodopago')),
                ('numero_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_user.persona')),
            ],
        ),
    ]
